name: Push Test

on:
  push:
    branches:
      - "release-v*.*.*"

jobs:
  update-log:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - name: Update log
        run: echo ${{github.ref}} | grep -P 'release-v[0-9]+\.[0-9]+\.[0-9]+' -o
        # run: echo "${{ github.ref }}" | grep -P 'release-v[0-9]+\.[0-9]+\.[0-9]+' -o
  # create-tag:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: rickstaa/action-create-tag@v1
  #       with:
  #         tag: "latest"
  #         message: "Latest release"
  #         force_push_tag: true
