name: Push Test

on:
  push:
    branches:
      - "release-v*.*.*"

jobs:
  update-log:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - name: Update log
        run: echo "Updating change log..."
