name: Release
on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  create-tag:
    name: "Create Version Tag"
    runs-on: ubuntu-latest
    outputs:
      tag-name: ${{steps.extr-version.outputs.version}}
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Extract Branch Name
        id: extr-version
        run: echo ${{github.head_ref}} | grep -P 'v[0-9]+\.[0-9]+\.[0-9]+' -o | echo "version=$(cat)" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{steps.extr-version.outputs.version}}"
          message: "Release ${{steps.extr-version.outputs.version}}"

  create-release:
    needs: create-tag
    name: "Create Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt

      - uses: softprops/action-gh-release@v1
        with:
          body_path: ${{github.workspace}}-CHANGELOG.txt
          tag_name: "${{needs.create-tag.outputs.tag-name}}"
          files: |
            README.md
