name: Release
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  create-tag:
    name: "Create Version Tag"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Extract Branch Name
        id: extr-version
        run: echo ${{github.ref}} | grep -P 'v[0-9]+\.[0-9]+\.[0-9]+' -o | echo "version=$(cat)"
        # run: echo ${{github.ref}} | grep -P 'v[0-9]+\.[0-9]+\.[0-9]+' -o | echo "version=$(cat)" >> $GITHUB_OUTPUT

      # - uses: rickstaa/action-create-tag@v1
      #   with:
      #     tag: "${{steps.extr-version.outputs.version}}"
      #     message: "Release ${{steps.extr-version.outputs.version}}"

  # create-release:
  #   name: "Create Release"
  #   runs-on: "ubuntu-latest"
  #   if: github.event.pull_request.merged == true
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         files: |
  #           README.md
